### ISSUE TITLE
Problem with the subs

### ISSUE THREAD

**Issue by TheNezk** [Stremio/stremio-opensubtitles#11]
Hi .. Most of the arabic subs like this. And someone told me that because Opensubtitles uses UTF-8 to decode arabic subtitles when Windows-1256 is better suited for this. So i don't know if that the reason but fix it PLEASE
![Screenshot_20201015-005107_Stremio](https://user-images.githubusercontent.com/72942419/96172124-98b76480-0f2e-11eb-81b9-4d07cddcf807.jpg)

**Comment by Ivshti** [comment]
@jaruba can you check this?

**Comment by jaruba** [comment]
@TheNezk Hi, arabic subtitles work absolutely fine in my tests:
<img width="499" alt="Screen Shot 2020-10-16 at 13 12 03" src="https://user-images.githubusercontent.com/1777923/96246471-5aaf5480-0fb1-11eb-9a92-2e61deec2c68.png">

In order to find out why they don't work for you, please answer these questions:
- what OS are you running Stremio on? (I tested on OSX)
- what subtitle addon are you using? (I tested with the official OpenSubtitles addon)
- what video have you tried and did not work (from which addon, what exact stream did you use)
- which variation of the subtitle did you use for your selected stream (there is usually more then one subtitle per language available, which variation number did you choose from the subtitles? if you did not change the variation at all, then it is expected that this answer should be "1")

**Comment by TheNezk** [comment]
@jaruba Thanks! I was using unofficial version (0.24.0) the official addon works perfect

**Comment by jaruba** [comment]
@TheNezk 

If you are in contact with the developer of the community addon that has this issue, please send him this link:
https://github.com/Stremio/stremio-addon-sdk/commit/ee78826c61bff497e70a5d758afdf29b284f4f0d

It explains how subtitle encodings can be handled better in subtitle addons.
