### ISSUE TITLE
Addon doesn't want to load subtitle from opensuibtitles

### ISSUE THREAD

**Issue by HaxWitcher** [Stremio/stremio-opensubtitles#25]
I added Serbian and Croatian for this movie( Bharat 2019) subtitles to opensubtitles, but even after three days, the subtitle is not available in stremio.

IMBD Movie: https://www.imdb.com/title/tt7721800/

I'm interested in what the problem is, because I see that the other subtitles are loading.

I'm also interested in how long it usually takes for the subtitle to be available in stremio after uploading to opensubtitles?

Thanks.

**Comment by jaruba** [comment]
@HaxWitcher There seems to indeed be an issue and our access to OpenSubtitles has been  limited without notice, we have started discussions with the OpenSubtitles admin in hopes of resolving this.

**Comment by HaxWitcher** [comment]
Thanks for your response!

I hope the problem will be solved because currently the situation with subtitles on the stremio app is very bad, especially for non-English speaking countries.

It would be good if you could somehow notify us when the problem is solved.

Thanks.

**Comment by jaruba** [comment]
@HaxWitcher Hi, this should be fixed by tomorrow (it was still working, but very slowly), we are making this repository private as it is an old implementation and we will implement the new api of opensubtitles.com

Thank you for reporting this and making us aware of the issue, we hope you're enjoying Stremio
